service: appointment-service

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1
  stage: dev
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:GetItem
        - dynamodb:Query
      Resource:
        - arn:aws:dynamodb:${self:provider.region}:*:table/AppointmentTable
    - Effect: Allow
      Action:
        - sns:Publish
      Resource:
        - ${self:custom.snsTopicArnPE}
        - ${self:custom.snsTopicArnCL}

    - Effect: Allow
      Action:
        - sqs:SendMessage
        - sqs:ReceiveMessage
        - sqs:DeleteMessage
      Resource:
        - arn:aws:sqs:${self:provider.region}:*:SQS_PE
        - arn:aws:sqs:${self:provider.region}:*:SQS_CL
        - arn:aws:sqs:${self:provider.region}:*:appointment-confirmation-queue

    - Effect: Allow
      Action:
        - events:PutEvents
      Resource: "*"

custom:
  snsTopicArnPE: arn:aws:sns:us-east-2:029636175630:appointment_PE.fifo
  snsTopicArnCL: arn:aws:sns:us-east-2:029636175630:appointment_CL.fifo
  esbuild:
    bundle: true
    minify: false
    sourcemap: true
    exclude: ['aws-sdk']
    target: node18
    platform: node
    concurrency: 10
  

  environment:
      APPOINTMENTS_TABLE: Appointments
      RDS_PE_HOST: pe-db.cluster-xxxxx.us-east-1.rds.amazonaws.com
      RDS_PE_USER: admin
      RDS_PE_PASSWORD: pe_password
      RDS_PE_DB: appointments_pe
      RDS_CL_HOST: cl-db.cluster-yyyyy.us-east-1.rds.amazonaws.com
      RDS_CL_USER: admin
      RDS_CL_PASSWORD: cl_password
      RDS_CL_DB: appointments_cl

# functions for lambda with endpoints
functions:
  appointment:
    handler: src/lambdas/appointment.handler
    events:
      - http:
          path: appointments
          method: post
      - http:
          path: appointments/{insuredId}
          method: get
      - sqs:
          arn:
            Fn::GetAtt: [AppointmentConfirmationQueue, Arn]

  appointment_pe:
    handler: src/lambdas/appointment_pe.handler
    events:
      - sqs:
          arn:
            Fn::GetAtt: [SQSPEQueue, Arn]
  
  appointment_cl:
    handler: src/lambdas/appointment_cl.handler
    events:
      - sqs:
          arn:
            Fn::GetAtt: [SQSCLQueue, Arn]

plugins:
  # - serverless-esbuild
  - serverless-offline

package:
  individually: true


resources:
  Resources:
    AppointmentTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: AppointmentTable
        AttributeDefinitions:
          - AttributeName: insuredId
            AttributeType: S
          - AttributeName: scheduleId
            AttributeType: N
        KeySchema:
          - AttributeName: insuredId
            KeyType: HASH
          - AttributeName: scheduleId
            KeyType: RANGE
        BillingMode: PAY_PER_REQUEST
    SQSPEQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: SQS_PE
    SQSCLQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: SQS_CL
    AppointmentConfirmationQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: appointment-confirmation-queue
    AppointmentConfirmedRule:
      Type: AWS::Events::Rule
      Properties:
        EventPattern:
          source:
            - "appointment.service"
          detail-type:
            - "AppointmentConfirmed"
        Targets:
          - Arn:
              Fn::GetAtt: [AppointmentConfirmationQueue, Arn]
            Id: "SendToConfirmationQueue"
